# Generated by Django 4.1 on 2023-06-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductName", models.CharField(max_length=255)),
                ("ProductDescription", models.CharField(max_length=255)),
            ],
        ),
    ]
