# Generated by Django 4.1 on 2023-06-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="OtherDetails",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="ProductPrice",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="ProductStock",
            field=models.IntegerField(null=True),
        ),
    ]
