# Generated by Django 4.1 on 2023-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_products_otherdetails_products_productprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="ProductsCategory",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
